### PR TITLE
Fix several indentation problems, following ruby best practices guide

### PR DESCRIPTION
**Pull request by marceloboeira**
- 'New' hash syntax
- Blank Spaces
- Repeated code

### CODE REVIEW

**Comment by joncalhoun** [comment]
@marceloboeira Thanks for the initiative, but chances are we aren't going to be able to accept this PR as switching to the new hash syntax causes the library to stop working in ruby 1.8.7.

**Comment by marceloboeira** [comment]
@joncalhoun well, you shouldn't just stop improving your code just because you would not support old ruby versions... You really should explore the possibility of keeping the legacy code on a 1.x version/branch, and a 2.x version with support and future improvements...

**Comment by marvin52** [comment]
:clap:

**Comment by joncalhoun** [comment]
@marceloboeira We are still improving the code. We are just opting to use the 1.8.7 style hashes so that the improvements also work for older ruby versions without having to manage two gem versions.

**Comment by marceloboeira** [comment]
:disappointed:

**Pull request closed without merging**
